export const enum Reason {
  PRO = 'PRO',
  SUPERMARKET = 'SUPERMARKET',
  HEALTH = 'HEALTH',
  ASSISTANCE_TO_VULNERABLE_PEOPLE = 'ASSISTANCE_TO_VULNERABLE_PEOPLE',
  INDIVIDUAL_PHYSICAL_ACTIVITY = 'INDIVIDUAL_PHYSICAL_ACTIVITY'
}
